# Generated by Django 4.1 on 2022-08-09 04:34

from django.db import migrations, models

# python manage.py makemigrations stu   创建牵引文件
# python manage.py migrate  执行所有牵引文件

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30, unique=True)),
                ('spwd', models.CharField(max_length=30)),
            ],
        ),
    ]
