# Generated by Django 4.1 on 2022-08-10 14:27

from django.db import migrations, models

# python manage.py makemigrations stu   创建牵引文件
# python manage.py migrate stu  执行牵引文件

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=30)),
                ('gdesc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('count', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gimg', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
