# Generated by Django 4.1 on 2022-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('areaid', models.IntegerField(primary_key=True, serialize=False)),
                ('areaname', models.CharField(blank=True, max_length=255, null=True)),
                ('parentid', models.IntegerField(blank=True, null=True)),
                ('arealevel', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
    ]
