# Generated by Django 4.1 on 2022-08-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clazz',
            options={'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stu.clazz', verbose_name='班级'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clazz',
            name='cname',
            field=models.CharField(max_length=30, unique=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=30, unique=True, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='student',
            name='son',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='学号'),
        ),
    ]
